Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  config.trigger.before :up do |trigger|
    trigger.run = {
      inline: "bash -c 'mkdir -p ~/goinfre/\"VirtualBox VMs\" && VBoxManage setproperty machinefolder ~/goinfre/\"VirtualBox VMs\"'"
    }
  end

  config.vm.define "thi-phngS" do |server|
    server.vm.hostname = "thi-phngS"
    server.vm.network "private_network", ip: "192.168.56.110"
    # On copie le dossier confs/ dans la VM
    server.vm.synced_folder "confs/", "/home/vagrant/confs"
    server.vm.provision "shell", path: "scripts/server.sh"
  end
end
