Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = false

  # Config hardware for VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # Store VirtualBox VMs in ~/goinfre (42 home disk quota) instead of ~/VirtualBox VMs
  config.trigger.before :up do |trigger|
    trigger.run = {
      inline: "bash -c 'mkdir -p ~/goinfre/\"VirtualBox VMs\" && VBoxManage setproperty machinefolder ~/goinfre/\"VirtualBox VMs\"'"
    }
  end

  # Machine 1: Server
  config.vm.define "thi-phngS" do |server|
    server.vm.hostname = "thi-phngS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  # Machine 2: Worker
  config.vm.define "thi-phngSW" do |worker|
    worker.vm.hostname = "thi-phngSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
